<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Authors>Matt Bentley</Authors>
		<Version>1.1.0</Version>
		<Product>MiniTransit</Product>
		<Description>MiniTransit is a lightweight, extensible .NET messaging library. RabbitMQ MiniTransit implementation.</Description>
		<PackageProjectUrl>https://github.com/matt-bentley/MiniTransit</PackageProjectUrl>
		<RepositoryUrl>https://github.com/matt-bentley/MiniTransit</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MiniTransit\MiniTransit.csproj" />
	</ItemGroup>

</Project>
